Layout/EndOfLine:
  Enabled: false
Layout/IndentationWidth:
  Width: 1
Layout/LineLength:
  Enabled: false
Layout/Tab:
  Enabled: false
  IndentationWidth: 2
Layout/TrailingEmptyLines:
  Enabled: false
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Metrics/BlockLength:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false