Layout/EndOfLine:
  Enabled: false
Layout/IndentationStyle:
  EnforcedStyle: tabs
  IndentationWidth: 2
Layout/IndentationWidth:
  Width: 1
Layout/LineLength:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Layout/TrailingEmptyLines:
  Enabled: false
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Metrics/BlockLength:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/ExponentialNotation:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true