language: ruby
rvm: 2.6.3
before_install:
  - gem update --system
  - gem install bundler
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
before_script:
  - psql --version
  - psql -c 'CREATE DATABASE omweso_test;' -U postgres
  - psql -c "CREATE USER omweso WITH PASSWORD 'mancala';" -U postgres
  - psql -c "GRANT ALL ON DATABASE omweso_test TO omweso;" -U postgres
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: YxqbiExNDjeUzqXgUOu9wylb7R1EpiGBversoBnaU3xdfiSbYVIPm/n/JZGFPm7nTtwHjr7//gtX+axgnhHrG1CtcFNAsz1FQ7NoOV73bN2xU1QrLVGuzYe9hYA36yRpzaWb860+E4rhacm03cJh+RmvDGVArUQNkS6t+yohKzvKS59PNZa1jZ6Z9eGgQUqlA8AcGkrwmoE8LSVavlC5604LdaxLvVkpjXGo0d5FtWz96L7sBaYYrAmHsgxiyABOIVZtSrjJqyS7NyvjNCSfl9WyWxjXnxoYF2QmFuE5YmD7k9eO0YJO8z6SI5qA4psHIsFz68Ea2K9od0EwOO9DXLGdIkea2OskMWKnrC4NLZfNoAnF7QUs25Ge+poyrr+lzQLVUpHU+tAg7GDP2qkzUIomOi6LQx+9UCPl/U8eiLdlvuDU/Lwk1nA/tejrZigJDYsGSxCJtxSST7uEPWdIse7Brsyo/lyYEnL5CM3bvAwGyic8eDU7wzI+60/ii4i/HoqrTWlW/ERGwdbFH5b1nuD9KF8cOQ2w9y1ImYo4+pAx/K6ysN9EemgjBY3yvv1dCXOEI5/Z5nadbI+NzALJa1QXlz7jQMJrOoYombZbMFIcQgndw/48PFqxVoI+adnokCSTxPQXk36ea185sXsdLbPfQ2OjDHsAxAaSfFKQaxo=
notifications:
  email:
    on_success: change
    on_failure: always
services:
  - postgresql
addons:
  postgresql: "11.4"