language: ruby
rvm: 2.7.0
env:
  - DATABASE_URL=postgres://omweso:mancala@localhost/omweso_test
before_install:
  - gem install bundler
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
before_script:
  - psql --version
  - psql -c 'CREATE DATABASE omweso_test;' -U postgres
  - psql -c "CREATE USER omweso WITH PASSWORD 'mancala';" -U postgres
  - psql -c "GRANT ALL ON DATABASE omweso_test TO omweso;" -U postgres
script:
  - bundle exec rubocop
  - bundle exec rake sequel:migrate
  - bundle exec rake
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: ocVE+Y9uvrljVftVheEJ9pYqzwDH3t+wY02/VYGNYVZNFod5DP2N2MiNGn1mM7Abw9DkvJsB0Wlc2DN0h1XhhxA5CPfC/NNZA//M4vxRB9JG+mqO+DL/yeKDpnXiANyaCEY2iwA/cRfLMf8gNs2R6w/cwEQycI59sAfddzm6VPRjDr0sWP3AGbKQ/Vbpe+wPbm/LoYSD6z6I65RzyzNIGe3zszM9/Z7qhKYOYMv6CKtNrB1qdayyT/SPVh2VrslMjGGJTPtYe3lnhqTpSjgPnUg+05qQ1Tj2NQuAo3Id3bJzBixacwNsKNY25XcrKJTf1ekSe5FtewxNiWlI91Osv6HK8xa/YwpvAagbmMz0EXA1mlXg1nvx5Ow/CCTqUctxqmcCQKb+4WUpQzLyweZ9Q4e0bZWP0a42WmX5jW41FAKCbCoznQj+ikFFJNWzwSIzu3SCTbtwhFhsLHm/w2AaBTMbAeSDeXnBDJ5bXsBN/4+ikFvYyoV0QJqU3cbAEaBb+88DaQYbtv1pl+EGEu74TN5bWtmJaGYpSmnjT0H5nmLSQBvTvvFYKHqhlYtHIgrHekSGc07vRI2y8dF6p8pR2UDU3A8NVKg5HGCLAG6dqB1fZpGOIeGSC1X+dygt4BPJXrWtQUalUcCqrEtT3MIyg4HTwakYTKUyi+CWjnD2/wE=
notifications:
  email:
    on_success: change
    on_failure: always
services:
  - postgresql
  - rabbitmq
addons:
  postgresql: "11.6"
  apt:
    packages:
      - rabbitmq-server