language: ruby
rvm: 2.7.0
env:
  - DATABASE_URL=postgres://omweso:mancala@localhost/omweso_test
before_install:
  - gem install bundler
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-12 postgresql-client-12
  - sudo cp /etc/postgresql/{9.6,12}/main/pg_hba.conf
  - sudo service postgresql restart 12
before_script:
  - psql --version
  - psql -c 'CREATE DATABASE omweso_test;' -U postgres
  - psql -c "CREATE USER omweso WITH PASSWORD 'mancala';" -U postgres
  - psql -c "GRANT ALL ON DATABASE omweso_test TO omweso;" -U postgres
script:
  - bundle exec rubocop
  - bundle exec rake sequel:migrate
  - bundle exec rake
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: ZneFkLYgh4/gLZL444EgVMDMVCgSM+yhBSkOdEH6exuSEGOift8SNuSKL2EVkdDiNkBqjc76F5efKB6ZzHKKB7lRID4grFRMixJAl0m/G68+y3TVtTJ6k1OtqEXu6d3S8PDY1YZr2+cnYcAteSbfwzTyRtmiw0xoxuFnAajF2XtzOapAEi3x5vVtPvYb8Z9XRP7W0cZDW8S9L2zmo2zFmLhFmW3kzD4cKXYQiQ/KaXCP+HSM/GB5BDdcw5+Up6bbHu5zZNxcCfSuW9ySKXc37Z3TnFIHBvRRfHGuVgbvU1i6Lffg5RXtWzozAWNr8UPXmAOeMBOShFRbxcLbaBdlaTJSZKvNPb4oMrnMRW5/Bcu/OtpOdzmR8YAVqgUcR/efPjtxVbQst9BEdBzbY1FK6sPczPxm4gcy+HOL1dKTKQQNktWtIe9nnr2ZidnhJ8cD+DSwcFY5VO/kedF9wEo0TRKIHoKgbaYCeSH56UVTv9w8wPAxLdhZifMNrWyC2+qJhxKzjMqUHMZAr5l8LGOOqjAZOMX/u3++mbqcsOLIGZEIELKKjmbtwBuyabyarKWLSdcI+8v5I325VHqXIbGKlXROoYRhQj6yM7nq6ZidF/A0Yw6J1Iaxx0ooAJHGF7LOiOZW2Lxt0ZfOsn28GmqNNmK5xgFb3+1rzPoKKeY+lJg=
notifications:
  email:
    on_success: change
    on_failure: always
services:
  - postgresql
  - rabbitmq
addons:
  postgresql: "12.1"
  apt:
    packages:
      - rabbitmq-server