language: ruby
rvm: 2.7.0
env:
  - DATABASE_URL=postgres://omweso:mancala@localhost/omweso_test
before_install:
  - gem install bundler
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
before_script:
  - psql --version
  - psql -c 'CREATE DATABASE omweso_test;' -U postgres
  - psql -c "CREATE USER omweso WITH PASSWORD 'mancala';" -U postgres
  - psql -c "GRANT ALL ON DATABASE omweso_test TO omweso;" -U postgres
script:
  - bundle exec rubocop
  - bundle exec rake sequel:migrate
  - bundle exec rake
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: N2YUna7ZRSpeyQEPdVUuBg20ZbnZXBQhaY6pbfQRCbf65p3EgCVbRF4Iqb1Wy0z1ilFRgZyU08J/9R5LeNxDvyJTITZx8QEhfTLARtNBp7t1fql9Agnt/qFnSvetKHhocZ2tgaeR9Y41iRH8ia2zQa83kZ6AObo7k67YEhmia+lncxGsdPuaAL8E24FpVe9BV7QF2NBXd6SHo4br+BNsVN1oljs8tcxyk2XhQ9x00eoY6rmT/M4PP0kdkC9brbmaTeINE/sQTJ0PKhr5bauCDWCMe5eIJ/+fbB4AkECBJF9KFYx2V47oYgDm+uCFdAsBNlsOpbCyBCT+Q+PfabUl0T0W9WBFe8GPHsCXwq6/CT4E1Z2ydDxd+QV29OF/zyOzuAWtOM8COp9KqEwHPYpG1A6Ors1wXGOTTrAXYtlq56NAEU7OWezzSppC3pr5WZXU3RLeQBBir6dfKnBWPQbxZAb8+hYDPA9+9oxL5gM3/+aFB1BnHtWeKekukHaLavJQBoMf3KmZRPM50xBtZ0L1/Ch7EcCRNQLTRMpJz0NyYswDcVKnYh3PtC+V2s0JWeKodr+SUn6h/Y79cdqChUJ+qx+ST/PvTRZNF814DKhtKoG6LHN0ph+oLa/u3zf1uuyMCzSGtbgCzI7qxn//M8QOrhguENaqHQKjPdKzgx9MWdg=
notifications:
  email:
    on_success: change
    on_failure: always
services:
  - postgresql
  - rabbitmq
addons:
  postgresql: "11.6"
  apt:
    packages:
      - rabbitmq-server