common: &default_settings
  license_key: '<%= ENV["NEW_RELIC_LICENSE_KEY"] %>'
  app_name: Omweso
  agent_enabled: false
  log_level: info

development:
  <<: *default_settings
test:
  <<: *default_settings
production:
  <<: *default_settings
  agent_enabled: true
