common: &default_settings
  license_key: 39163f4b6838580879b68387c17c68afbb66f336
  app_name: Omweso
  agent_enabled: false
  log_level: info

development:
  <<: *default_settings
test:
  <<: *default_settings
production:
  <<: *default_settings
  agent_enabled: true
