development:
  name: omweso-dev
  log_level: trace
  pretty_logs: true
test:
  name: omweso-test
  log_level: fatal
  pretty_logs: false
production:
  name: omweso-prod
  log_level: info
  pretty_logs: false